In [3]:
import torch
print(torch.__version__)

2.12.1+cpu


## Introduction to Tensors

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
#Dimension (number of brackets)
print(scalar.ndim)
# Get tensor back as python int
print(scalar.item())

0
7


In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
#Dimension
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
print(MATRIX.ndim)
print(MATRIX.shape)
print()
print(MATRIX[0])
print(MATRIX[1])
print()
print(MATRIX[0][0])
print(MATRIX[0][1])
print(MATRIX[1][0])
print(MATRIX[1][1])
print()
print(MATRIX[0,0])
print(MATRIX[0,1])
print(MATRIX[1,0])
print(MATRIX[1,1])

2
torch.Size([2, 2])

tensor([7, 8])
tensor([ 9, 10])

tensor(7)
tensor(8)
tensor(9)
tensor(10)

tensor(7)
tensor(8)
tensor(9)
tensor(10)


In [10]:
# tensor
TENSOR = torch.tensor([[[1,2,3,4,5],
                        [4,5,6,7,8],
                        [7,8,9,10,11]]])
TENSOR

tensor([[[ 1,  2,  3,  4,  5],
         [ 4,  5,  6,  7,  8],
         [ 7,  8,  9, 10, 11]]])

In [11]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 5])


In [12]:
TENSOR[0]

tensor([[ 1,  2,  3,  4,  5],
        [ 4,  5,  6,  7,  8],
        [ 7,  8,  9, 10, 11]])

In [13]:
TENSOR[0,0]

tensor([1, 2, 3, 4, 5])

In [14]:
TENSOR[0,0,0]

tensor(1)

### Random tensors

In [15]:
random_tensor = torch.rand(3,4,2)
random_tensor

tensor([[[0.5026, 0.6053],
         [0.4623, 0.6586],
         [0.2765, 0.6395],
         [0.0868, 0.6434]],

        [[0.6588, 0.3267],
         [0.3723, 0.3237],
         [0.7838, 0.6459],
         [0.1386, 0.0882]],

        [[0.8917, 0.3163],
         [0.4874, 0.6811],
         [0.0269, 0.1104],
         [0.3790, 0.4327]]])

In [16]:
print(random_tensor.ndim)
print(random_tensor.shape)

3
torch.Size([3, 4, 2])


In [17]:
random_tensor = torch.rand(1,2,3,3,3)
random_tensor

tensor([[[[[0.4505, 0.8448, 0.5119],
           [0.0450, 0.8490, 0.8697],
           [0.5063, 0.6389, 0.6402]],

          [[0.3412, 0.5884, 0.3212],
           [0.7987, 0.6044, 0.8745],
           [0.6362, 0.9693, 0.9486]],

          [[0.0456, 0.6422, 0.4695],
           [0.7628, 0.5740, 0.5285],
           [0.2658, 0.4348, 0.8166]]],


         [[[0.9577, 0.5771, 0.2879],
           [0.1247, 0.1066, 0.3676],
           [0.9484, 0.7107, 0.5229]],

          [[0.9352, 0.8562, 0.4661],
           [0.3159, 0.2242, 0.5563],
           [0.9982, 0.7458, 0.0537]],

          [[0.8966, 0.4295, 0.2188],
           [0.6821, 0.6348, 0.5584],
           [0.2935, 0.5511, 0.2930]]]]])

In [18]:
print(random_tensor.ndim)
print(random_tensor.shape)

5
torch.Size([1, 2, 3, 3, 3])


In [19]:
# similar tensor image shape
random_image_size_tensor = torch.rand(3,224,244) #colour channels,height, width
print(random_image_size_tensor.ndim)
print(random_image_size_tensor.shape)

3
torch.Size([3, 224, 244])


In [27]:
rand = torch.rand(size=(3,4))
rand

tensor([[0.2754, 0.1414, 0.5938, 0.6255],
        [0.8679, 0.6005, 0.1038, 0.1667],
        [0.8786, 0.7199, 0.8346, 0.3875]])

In [24]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
zero * rand

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Creating a range of tensor and tensors-like

In [38]:
one_to_ten = torch.arange(start=1,end=11,step=1.1)
one_to_ten

tensor([ 1.0000,  2.1000,  3.2000,  4.3000,  5.4000,  6.5000,  7.6000,  8.7000,
         9.8000, 10.9000])

In [37]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor data types

In [40]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=int)
float_32_tensor

tensor([3, 6, 9])

In [44]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float32)
float_32_tensor.dtype

torch.float32

tensor 3 big errors
1.- tensors not rigth datatype
2.- tensors not right shape
3.- tensors not on the rigth device

In [ ]:
#parametros mas importantes al crear tensores
tensor = torch.tensor([1.0,2.0,3.0],
                      dtype=None, # what datatype is the tensor
                      device=None,# what device is ur tensor on
                      requires_grad=False) #whether or not to track gradients with this tensors operations

In [47]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [49]:
float_16_tensor * float_32_tensor


tensor([ 9., 36., 81.])

In [50]:
int_32_tensor = torch.tensor([3,6,8], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [52]:
some_tensor = torch.rand([3,5])

In [54]:
# Details about some tensor
print(some_tensor)
print(f'Datatype of tensor:{some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.7882, 0.5469, 0.6875, 0.6047, 0.3388],
        [0.6963, 0.8131, 0.8681, 0.0993, 0.4411],
        [0.5491, 0.1423, 0.8462, 0.0784, 0.5285]])
Datatype of tensor:torch.float32
Shape of tensor: torch.Size([3, 5])
Device tensor is on: cpu
