In [1]:
import torch
print(torch.__version__)

2.14.0.dev20260628+cu132


## Introduction to Tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
#Dimension (number of brackets)
print(scalar.ndim)
# Get tensor back as python int
print(scalar.item())

0
7


In [4]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
#Dimension
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [6]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
print(MATRIX.ndim)
print(MATRIX.shape)
print()
print(MATRIX[0])
print(MATRIX[1])
print()
print(MATRIX[0][0])
print(MATRIX[0][1])
print(MATRIX[1][0])
print(MATRIX[1][1])
print()
print(MATRIX[0,0])
print(MATRIX[0,1])
print(MATRIX[1,0])
print(MATRIX[1,1])

2
torch.Size([2, 2])

tensor([7, 8])
tensor([ 9, 10])

tensor(7)
tensor(8)
tensor(9)
tensor(10)

tensor(7)
tensor(8)
tensor(9)
tensor(10)


In [8]:
# tensor
TENSOR = torch.tensor([[[1,2,3,4,5],
                        [4,5,6,7,8],
                        [7,8,9,10,11]]])
TENSOR

tensor([[[ 1,  2,  3,  4,  5],
         [ 4,  5,  6,  7,  8],
         [ 7,  8,  9, 10, 11]]])

In [9]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 5])


In [10]:
TENSOR[0]

tensor([[ 1,  2,  3,  4,  5],
        [ 4,  5,  6,  7,  8],
        [ 7,  8,  9, 10, 11]])

In [11]:
TENSOR[0,0]

tensor([1, 2, 3, 4, 5])

In [12]:
TENSOR[0,0,0]

tensor(1)

### Random tensors

In [13]:
random_tensor = torch.rand(3,4,2)
random_tensor

tensor([[[0.1591, 0.1978],
         [0.4591, 0.9646],
         [0.0744, 0.6796],
         [0.8012, 0.0883]],

        [[0.6276, 0.3982],
         [0.0969, 0.5300],
         [0.5985, 0.1292],
         [0.3655, 0.8486]],

        [[0.6490, 0.2894],
         [0.2711, 0.4882],
         [0.8487, 0.0582],
         [0.0140, 0.7404]]])

In [14]:
print(random_tensor.ndim)
print(random_tensor.shape)

3
torch.Size([3, 4, 2])


In [15]:
random_tensor = torch.rand(1,2,3,3,3)
random_tensor

tensor([[[[[0.4148, 0.3258, 0.2778],
           [0.7199, 0.4135, 0.5548],
           [0.7955, 0.6996, 0.9322]],

          [[0.6429, 0.3618, 0.4925],
           [0.3724, 0.6968, 0.8925],
           [0.9077, 0.4071, 0.7007]],

          [[0.6837, 0.7876, 0.9018],
           [0.0401, 0.9983, 0.5464],
           [0.3705, 0.3407, 0.7370]]],


         [[[0.6336, 0.7576, 0.0467],
           [0.5510, 0.9321, 0.7755],
           [0.2994, 0.6529, 0.7873]],

          [[0.3984, 0.7941, 0.0968],
           [0.5629, 0.6980, 0.3524],
           [0.1829, 0.9136, 0.4756]],

          [[0.7956, 0.3981, 0.9578],
           [0.3953, 0.2632, 0.0259],
           [0.0633, 0.8499, 0.0405]]]]])

In [16]:
print(random_tensor.ndim)
print(random_tensor.shape)

5
torch.Size([1, 2, 3, 3, 3])


In [17]:
# similar tensor image shape
random_image_size_tensor = torch.rand(3,224,244) #colour channels,height, width
print(random_image_size_tensor.ndim)
print(random_image_size_tensor.shape)

3
torch.Size([3, 224, 244])


In [18]:
rand = torch.rand(size=(3,4))
rand

tensor([[0.6699, 0.0118, 0.8828, 0.4250],
        [0.7793, 0.8037, 0.3071, 0.9080],
        [0.3463, 0.5466, 0.8153, 0.9287]])

In [19]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zero * rand

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Creating a range of tensor and tensors-like

In [22]:
one_to_ten = torch.arange(start=1,end=11,step=1.1)
one_to_ten

tensor([ 1.0000,  2.1000,  3.2000,  4.3000,  5.4000,  6.5000,  7.6000,  8.7000,
         9.8000, 10.9000])

In [23]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Tensor data types

In [24]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=int)
float_32_tensor

tensor([3, 6, 9])

In [25]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float32)
float_32_tensor.dtype

torch.float32

tensor 3 big errors
1.- tensors not rigth datatype
2.- tensors not right shape
3.- tensors not on the rigth device

In [26]:
#parametros mas importantes al crear tensores
tensor = torch.tensor([1.0,2.0,3.0],
                      dtype=None, # what datatype is the tensor
                      device=None,# what device is ur tensor on
                      requires_grad=False) #whether or not to track gradients with this tensors operations

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [28]:
float_16_tensor * float_32_tensor


tensor([ 9., 36., 81.])

In [29]:
int_32_tensor = torch.tensor([3,6,8], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [30]:
some_tensor = torch.rand([3,5])

In [31]:
# Details about some tensor
print(some_tensor)
print(f'Datatype of tensor:{some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.9005, 0.4431, 0.1057, 0.5017, 0.8120],
        [0.1033, 0.7625, 0.6451, 0.1556, 0.6159],
        [0.9185, 0.1902, 0.6208, 0.9150, 0.7741]])
Datatype of tensor:torch.float32
Shape of tensor: torch.Size([3, 5])
Device tensor is on: cpu


### Manipulating tensors
 * Adittion 
 * Substraction
 * Division
 * Multiplication (element-wise)
 * Matrix Multiplication


In [32]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [33]:
tensor - 10

tensor([-9, -8, -7])

In [34]:
tensor * 10

tensor([10, 20, 30])

In [35]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [36]:
print(torch.add(tensor,10))
print(torch.sub(tensor,10))
print(torch.mul(tensor,10))
print(torch.div(tensor,10))

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


### matrix multiplication
#### element wise multiplication
#### matrix multiplication (dot product)

In [37]:
#element wise multiplication
print(f"{tensor} * {tensor} = {tensor*tensor}") # nos da la multiplicacion de cada elemento

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [38]:
#matrix multiplication
torch.matmul(tensor, tensor) #Da el producto punto (Suma de las multiplicaciones)

tensor(14)

In [39]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 2 ms


In [40]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

#### Inner dimension must match
#### the resulting matrix has the shape of the outer dimensions

* (3,2) @ (3,2) # Error
* (3,2) @ (2,3) # Correct
* (2,3) @ (3,2) # Correct

In [41]:
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [42]:
ma = torch.matmul(torch.rand(3,2), torch.rand(2,3))
print(ma)
print(ma.shape)

tensor([[0.1764, 0.1729, 0.1374],
        [0.3976, 0.2678, 0.3605],
        [0.1803, 0.1467, 0.1530]])
torch.Size([3, 3])


In [43]:
ma =torch.matmul(torch.rand(1,3), torch.rand(3,2))
print(ma)
print(ma.shape)

tensor([[0.8053, 0.9739]])
torch.Size([1, 2])


In [44]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix tensor issues, we can manipulate the shape of one of our tensor using transponse

In [45]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [46]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [47]:
torch.matmul(tensor_A, tensor_B.T), torch.matmul(tensor_A, tensor_B.T).shape 

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

### Tensor aggregation

In [48]:
x = torch.arange(0,100, 10)

In [49]:
print(torch.min(x), x.min())
print(torch.max(x), x.max())
print(torch.sum(x), x.sum())
print(torch.mean(x.type(torch.float32)), x.type(torch.float32).mean())



tensor(0) tensor(0)
tensor(90) tensor(90)
tensor(450) tensor(450)
tensor(45.) tensor(45.)


finding position max min

In [ ]:
print(x.argmax())
print(x.argmin())


tensor(9)
tensor(0)


In [51]:
x[9]

tensor(90)