In [33]:
import torch
print(torch.__version__)

2.12.1+cpu


## Introduction to Tensors

In [34]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [35]:
#Dimension (number of brackets)
print(scalar.ndim)
# Get tensor back as python int
print(scalar.item())

0
7


In [36]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [37]:
#Dimension
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [38]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [39]:
print(MATRIX.ndim)
print(MATRIX.shape)
print()
print(MATRIX[0])
print(MATRIX[1])
print()
print(MATRIX[0][0])
print(MATRIX[0][1])
print(MATRIX[1][0])
print(MATRIX[1][1])
print()
print(MATRIX[0,0])
print(MATRIX[0,1])
print(MATRIX[1,0])
print(MATRIX[1,1])

2
torch.Size([2, 2])

tensor([7, 8])
tensor([ 9, 10])

tensor(7)
tensor(8)
tensor(9)
tensor(10)

tensor(7)
tensor(8)
tensor(9)
tensor(10)


In [40]:
# tensor
TENSOR = torch.tensor([[[1,2,3,4,5],
                        [4,5,6,7,8],
                        [7,8,9,10,11]]])
TENSOR

tensor([[[ 1,  2,  3,  4,  5],
         [ 4,  5,  6,  7,  8],
         [ 7,  8,  9, 10, 11]]])

In [41]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 5])


In [42]:
TENSOR[0]

tensor([[ 1,  2,  3,  4,  5],
        [ 4,  5,  6,  7,  8],
        [ 7,  8,  9, 10, 11]])

In [43]:
TENSOR[0,0]

tensor([1, 2, 3, 4, 5])

In [44]:
TENSOR[0,0,0]

tensor(1)

### Random tensors

In [48]:
random_tensor = torch.rand(3,4,2)
random_tensor

tensor([[[0.0812, 0.1323],
         [0.8364, 0.8512],
         [0.4904, 0.5932],
         [0.2125, 0.1994]],

        [[0.0523, 0.3667],
         [0.2310, 0.7088],
         [0.2895, 0.0369],
         [0.6099, 0.4786]],

        [[0.8487, 0.5704],
         [0.2129, 0.6102],
         [0.5091, 0.5113],
         [0.3753, 0.6717]]])

In [50]:
print(random_tensor.ndim)
print(random_tensor.shape)

3
torch.Size([3, 4, 2])


In [54]:
random_tensor = torch.rand(1,2,3,3,3)
random_tensor

tensor([[[[[0.7454, 0.8816, 0.7254],
           [0.1567, 0.0011, 0.7100],
           [0.2975, 0.8519, 0.4665]],

          [[0.0299, 0.1535, 0.1384],
           [0.8460, 0.6536, 0.7780],
           [0.1395, 0.2031, 0.7693]],

          [[0.0181, 0.2850, 0.9090],
           [0.1893, 0.7253, 0.0703],
           [0.5782, 0.5500, 0.7465]]],


         [[[0.9594, 0.6037, 0.3284],
           [0.8804, 0.7200, 0.2680],
           [0.8805, 0.0432, 0.9287]],

          [[0.7182, 0.6196, 0.0053],
           [0.2163, 0.1034, 0.9222],
           [0.0165, 0.2386, 0.7385]],

          [[0.5355, 0.2012, 0.0867],
           [0.2062, 0.1292, 0.6473],
           [0.4304, 0.7959, 0.6946]]]]])

In [55]:
print(random_tensor.ndim)
print(random_tensor.shape)

5
torch.Size([1, 2, 3, 3, 3])


In [62]:
# similar tensor image shape
random_image_size_tensor = torch.rand(3,224,244) #colour channels,height, width
print(random_image_size_tensor.ndim)
print(random_image_size_tensor.shape)

3
torch.Size([3, 224, 244])
