In [4]:
import torch
print(torch.__version__)

2.12.1+cpu


## Introduction to Tensors

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
#Dimension (number of brackets)
print(scalar.ndim)
# Get tensor back as python int
print(scalar.item())

0
7


In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
#Dimension
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [9]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
print(MATRIX.ndim)
print(MATRIX.shape)
print()
print(MATRIX[0])
print(MATRIX[1])
print()
print(MATRIX[0][0])
print(MATRIX[0][1])
print(MATRIX[1][0])
print(MATRIX[1][1])
print()
print(MATRIX[0,0])
print(MATRIX[0,1])
print(MATRIX[1,0])
print(MATRIX[1,1])

2
torch.Size([2, 2])

tensor([7, 8])
tensor([ 9, 10])

tensor(7)
tensor(8)
tensor(9)
tensor(10)

tensor(7)
tensor(8)
tensor(9)
tensor(10)


In [11]:
# tensor
TENSOR = torch.tensor([[[1,2,3,4,5],
                        [4,5,6,7,8],
                        [7,8,9,10,11]]])
TENSOR

tensor([[[ 1,  2,  3,  4,  5],
         [ 4,  5,  6,  7,  8],
         [ 7,  8,  9, 10, 11]]])

In [12]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 5])


In [13]:
TENSOR[0]

tensor([[ 1,  2,  3,  4,  5],
        [ 4,  5,  6,  7,  8],
        [ 7,  8,  9, 10, 11]])

In [14]:
TENSOR[0,0]

tensor([1, 2, 3, 4, 5])

In [15]:
TENSOR[0,0,0]

tensor(1)

### Random tensors

In [16]:
random_tensor = torch.rand(3,4,2)
random_tensor

tensor([[[0.0116, 0.0530],
         [0.8675, 0.3126],
         [0.4637, 0.5165],
         [0.7171, 0.1346]],

        [[0.1237, 0.7506],
         [0.3524, 0.6614],
         [0.1032, 0.6897],
         [0.6193, 0.4649]],

        [[0.3983, 0.4541],
         [0.6689, 0.0913],
         [0.6024, 0.2229],
         [0.2052, 0.0301]]])

In [17]:
print(random_tensor.ndim)
print(random_tensor.shape)

3
torch.Size([3, 4, 2])


In [18]:
random_tensor = torch.rand(1,2,3,3,3)
random_tensor

tensor([[[[[0.0336, 0.5209, 0.4339],
           [0.4272, 0.1508, 0.5242],
           [0.5553, 0.2961, 0.2761]],

          [[0.5407, 0.0677, 0.3528],
           [0.7627, 0.5754, 0.3880],
           [0.1909, 0.6116, 0.3643]],

          [[0.9129, 0.2468, 0.3057],
           [0.7746, 0.4092, 0.7211],
           [0.1669, 0.2953, 0.9402]]],


         [[[0.5301, 0.7996, 0.5584],
           [0.0072, 0.9396, 0.2710],
           [0.3509, 0.3407, 0.6465]],

          [[0.3330, 0.3718, 0.5061],
           [0.2055, 0.9021, 0.0918],
           [0.1337, 0.2568, 0.5966]],

          [[0.9206, 0.3797, 0.5083],
           [0.6075, 0.0983, 0.6971],
           [0.1508, 0.6250, 0.6221]]]]])

In [19]:
print(random_tensor.ndim)
print(random_tensor.shape)

5
torch.Size([1, 2, 3, 3, 3])


In [20]:
# similar tensor image shape
random_image_size_tensor = torch.rand(3,224,244) #colour channels,height, width
print(random_image_size_tensor.ndim)
print(random_image_size_tensor.shape)

3
torch.Size([3, 224, 244])


In [21]:
rand = torch.rand(size=(3,4))
rand

tensor([[0.0695, 0.3468, 0.6696, 0.7063],
        [0.9419, 0.4100, 0.9192, 0.8165],
        [0.8779, 0.4206, 0.8046, 0.4071]])

In [22]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zero * rand

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Creating a range of tensor and tensors-like

In [25]:
one_to_ten = torch.arange(start=1,end=11,step=1.1)
one_to_ten

tensor([ 1.0000,  2.1000,  3.2000,  4.3000,  5.4000,  6.5000,  7.6000,  8.7000,
         9.8000, 10.9000])

In [26]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Tensor data types

In [27]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=int)
float_32_tensor

tensor([3, 6, 9])

In [28]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float32)
float_32_tensor.dtype

torch.float32

tensor 3 big errors
1.- tensors not rigth datatype
2.- tensors not right shape
3.- tensors not on the rigth device

In [29]:
#parametros mas importantes al crear tensores
tensor = torch.tensor([1.0,2.0,3.0],
                      dtype=None, # what datatype is the tensor
                      device=None,# what device is ur tensor on
                      requires_grad=False) #whether or not to track gradients with this tensors operations

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [31]:
float_16_tensor * float_32_tensor


tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3,6,8], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [33]:
some_tensor = torch.rand([3,5])

In [34]:
# Details about some tensor
print(some_tensor)
print(f'Datatype of tensor:{some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.3304, 0.6836, 0.0948, 0.3278, 0.1961],
        [0.5090, 0.9450, 0.3883, 0.4204, 0.6299],
        [0.1311, 0.1487, 0.7326, 0.3096, 0.1297]])
Datatype of tensor:torch.float32
Shape of tensor: torch.Size([3, 5])
Device tensor is on: cpu


### Manipulating tensors
 * Adittion 
 * Substraction
 * Division
 * Multiplication (element-wise)
 * Matrix Multiplication


In [36]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [38]:
tensor - 10

tensor([-9, -8, -7])

In [37]:
tensor * 10

tensor([10, 20, 30])

In [43]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [42]:
print(torch.add(tensor,10))
print(torch.sub(tensor,10))
print(torch.mul(tensor,10))
print(torch.div(tensor,10))

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])
