In [2]:
import torch
print(torch.__version__)

2.14.0.dev20260628+cu132


## Introduction to Tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
#Dimension (number of brackets)
print(scalar.ndim)
# Get tensor back as python int
print(scalar.item())

0
7


In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
#Dimension
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [7]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
print(MATRIX.ndim)
print(MATRIX.shape)
print()
print(MATRIX[0])
print(MATRIX[1])
print()
print(MATRIX[0][0])
print(MATRIX[0][1])
print(MATRIX[1][0])
print(MATRIX[1][1])
print()
print(MATRIX[0,0])
print(MATRIX[0,1])
print(MATRIX[1,0])
print(MATRIX[1,1])

2
torch.Size([2, 2])

tensor([7, 8])
tensor([ 9, 10])

tensor(7)
tensor(8)
tensor(9)
tensor(10)

tensor(7)
tensor(8)
tensor(9)
tensor(10)


In [9]:
# tensor
TENSOR = torch.tensor([[[1,2,3,4,5],
                        [4,5,6,7,8],
                        [7,8,9,10,11]]])
TENSOR

tensor([[[ 1,  2,  3,  4,  5],
         [ 4,  5,  6,  7,  8],
         [ 7,  8,  9, 10, 11]]])

In [10]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 5])


In [11]:
TENSOR[0]

tensor([[ 1,  2,  3,  4,  5],
        [ 4,  5,  6,  7,  8],
        [ 7,  8,  9, 10, 11]])

In [12]:
TENSOR[0,0]

tensor([1, 2, 3, 4, 5])

In [13]:
TENSOR[0,0,0]

tensor(1)

### Random tensors

In [14]:
random_tensor = torch.rand(3,4,2)
random_tensor

tensor([[[0.6045, 0.2054],
         [0.9071, 0.5031],
         [0.0884, 0.0112],
         [0.1330, 0.3725]],

        [[0.2793, 0.3319],
         [0.4438, 0.6418],
         [0.8861, 0.4124],
         [0.6529, 0.6803]],

        [[0.2284, 0.3721],
         [0.0872, 0.8533],
         [0.6732, 0.9845],
         [0.5600, 0.3375]]])

In [15]:
print(random_tensor.ndim)
print(random_tensor.shape)

3
torch.Size([3, 4, 2])


In [16]:
random_tensor = torch.rand(1,2,3,3,3)
random_tensor

tensor([[[[[0.2978, 0.2061, 0.7559],
           [0.7542, 0.8852, 0.2474],
           [0.8419, 0.5639, 0.3641]],

          [[0.7165, 0.5709, 0.8986],
           [0.3977, 0.0561, 0.9004],
           [0.6965, 0.8544, 0.3807]],

          [[0.0394, 0.1806, 0.1548],
           [0.7978, 0.4286, 0.9574],
           [0.2356, 0.1582, 0.7003]]],


         [[[0.8511, 0.1951, 0.2175],
           [0.2668, 0.7745, 0.8676],
           [0.4151, 0.8723, 0.8523]],

          [[0.2023, 0.5182, 0.4210],
           [0.3938, 0.3553, 0.2767],
           [0.9971, 0.2087, 0.4944]],

          [[0.0741, 0.2741, 0.9987],
           [0.4558, 0.9904, 0.0184],
           [0.4092, 0.7461, 0.8262]]]]])

In [17]:
print(random_tensor.ndim)
print(random_tensor.shape)

5
torch.Size([1, 2, 3, 3, 3])


In [18]:
# similar tensor image shape
random_image_size_tensor = torch.rand(3,224,244) #colour channels,height, width
print(random_image_size_tensor.ndim)
print(random_image_size_tensor.shape)

3
torch.Size([3, 224, 244])


In [19]:
rand = torch.rand(size=(3,4))
rand

tensor([[0.8640, 0.4007, 0.2172, 0.3554],
        [0.7210, 0.8163, 0.6886, 0.2510],
        [0.9266, 0.1845, 0.2721, 0.3669]])

In [20]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zero * rand

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Creating a range of tensor and tensors-like

In [23]:
one_to_ten = torch.arange(start=1,end=11,step=1.1)
one_to_ten

tensor([ 1.0000,  2.1000,  3.2000,  4.3000,  5.4000,  6.5000,  7.6000,  8.7000,
         9.8000, 10.9000])

In [24]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Tensor data types

In [25]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=int)
float_32_tensor

tensor([3, 6, 9])

In [26]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float32)
float_32_tensor.dtype

torch.float32

tensor 3 big errors
1.- tensors not rigth datatype
2.- tensors not right shape
3.- tensors not on the rigth device

In [27]:
#parametros mas importantes al crear tensores
tensor = torch.tensor([1.0,2.0,3.0],
                      dtype=None, # what datatype is the tensor
                      device=None,# what device is ur tensor on
                      requires_grad=False) #whether or not to track gradients with this tensors operations

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [29]:
float_16_tensor * float_32_tensor


tensor([ 9., 36., 81.])

In [30]:
int_32_tensor = torch.tensor([3,6,8], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [31]:
some_tensor = torch.rand([3,5])

In [32]:
# Details about some tensor
print(some_tensor)
print(f'Datatype of tensor:{some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.8682, 0.1421, 0.5370, 0.1632, 0.6275],
        [0.1283, 0.9134, 0.8239, 0.9879, 0.9012],
        [0.2036, 0.7399, 0.3049, 0.7522, 0.7941]])
Datatype of tensor:torch.float32
Shape of tensor: torch.Size([3, 5])
Device tensor is on: cpu


### Manipulating tensors
 * Adittion 
 * Substraction
 * Division
 * Multiplication (element-wise)
 * Matrix Multiplication


In [33]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [34]:
tensor - 10

tensor([-9, -8, -7])

In [35]:
tensor * 10

tensor([10, 20, 30])

In [36]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [37]:
print(torch.add(tensor,10))
print(torch.sub(tensor,10))
print(torch.mul(tensor,10))
print(torch.div(tensor,10))

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


### matrix multiplication
#### element wise multiplication
#### matrix multiplication (dot product)

In [42]:
#element wise multiplication
print(f"{tensor} * {tensor} = {tensor*tensor}") # nos da la multiplicacion de cada elemento

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [43]:
#matrix multiplication
torch.matmul(tensor, tensor) #Da el producto punto (Suma de las multiplicaciones)

tensor(14)

In [49]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 15.6 ms
Wall time: 0 ns


In [53]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

#### Inner dimension must match
#### the resulting matrix has the shape of the outer dimensions

* (3,2) @ (3,2) # Error
* (3,2) @ (2,3) # Correct
* (2,3) @ (3,2) # Correct

In [56]:
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [59]:
ma = torch.matmul(torch.rand(3,2), torch.rand(2,3))
print(ma)
print(ma.shape)

tensor([[0.2974, 0.5213, 0.7241],
        [0.2427, 0.6732, 0.4803],
        [0.2397, 0.4114, 0.5875]])
torch.Size([3, 3])


In [61]:
ma =torch.matmul(torch.rand(1,3), torch.rand(3,2))
print(ma)
print(ma.shape)

tensor([[0.5151, 0.5079]])
torch.Size([1, 2])
