In [ ]:
import torch
print(torch.__version__)

2.12.1+cpu


## Introduction to Tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
#Dimension (number of brackets)
print(scalar.ndim)
# Get tensor back as python int
print(scalar.item())

0
7


In [9]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [11]:
#Dimension
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [12]:
# Matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [21]:
print(matrix.ndim)
print(matrix.shape)
print()
print(matrix[0])
print(matrix[1])
print()
print(matrix[0][0])
print(matrix[0][1])
print(matrix[1][0])
print(matrix[1][1])
print()
print(matrix[0,0])
print(matrix[0,1])
print(matrix[1,0])
print(matrix[1,1])

2
torch.Size([2, 2])

tensor([7, 8])
tensor([ 9, 10])

tensor(7)
tensor(8)
tensor(9)
tensor(10)

tensor(7)
tensor(8)
tensor(9)
tensor(10)


In [28]:
# tensor
tensor = torch.tensor([[[1,2,3,4,5],
                        [4,5,6,7,8],
                        [7,8,9,10,11]]])
tensor

tensor([[[ 1,  2,  3,  4,  5],
         [ 4,  5,  6,  7,  8],
         [ 7,  8,  9, 10, 11]]])

In [29]:
print(tensor.ndim)
print(tensor.shape)

3
torch.Size([1, 3, 5])


In [30]:
tensor[0]

tensor([[ 1,  2,  3,  4,  5],
        [ 4,  5,  6,  7,  8],
        [ 7,  8,  9, 10, 11]])

In [31]:
tensor[0,0]

tensor([1, 2, 3, 4, 5])

In [32]:
tensor[0,0,0]

tensor(1)